version: '3'
services:

  service:
    build: app
    command: uwsgi --strict --ini uwsgi.ini
    expose:
      - "8000"
    volumes:
      - static_volume:/opt/app/static
      - media_volume:/opt/app/media
    env_file:
      - ./.env
    depends_on:
      - psql

  psql:
    # Образ и версия базы, которую мы будем использовать
    image: postgres:alpine
    # Внешний том(volume) и место где он будет подключен внутри контейнера
    volumes:
      - ./psql/create_schema.sql:/docker-entrypoint-initdb.d/create_schema.sql
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - 5432:5432

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
      - ./data:/data/:ro
      - static_volume:/opt/app/static
      - media_volume:/opt/app/media
    ports:
      - "80:80"
    depends_on:
      - service

  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./openapi.yaml:/swagger.yaml
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    depends_on:
      - nginx


volumes:
  static_volume:
  media_volume:
  postgres_data: